version: "3.6"
services:
  wordpress:
    build:
      context: .
      args:
        - php_version=8.4
    volumes:
      - wordpress_data:/var/www/html
      - nginx_cache:/var/run/nginx-cache
      - php_logs:/var/www/logs
    environment:
      WORDPRESS_TITLE: blogger
      WORDPRESS_PASSWORD: ch3ngeme
      WORDPRESS_URL: localhost
      WORDPRESS_EMAIL: admin@example.com
      WORDPRESS_USER: admin
      CS_AUTH_KEY: FcUpBTaoi746JbAdhWqJwtmXC0en1M3u
      METADATA_SERVICE: http://localhost
      METADATA_AUTH: foobar
    ports:
      - "80:80"

volumes:
  wordpress_data:
  nginx_cache:
  php_logs:
